Wiki
E2PC/ProjectPage pull request #35
Opened 2022-04-07 00:30 UTC by EricAKPM

Wiki

2022-04-07 23:11 UTC, AlexandroLuis commented
Favor apenas incluir atualização já em pleno funcioamento, não arquivos deletados, como por exemplo, "[Delete wiki/image directory](https://github.com/E2PC/ProjectPage/pull/35/commits/5eb5c85f18daf8fb76468f9c1094a7f86221c4a5)", "[Delete Uri_envio.png](https://github.com/E2PC/ProjectPage/pull/35/commits/32445f99042d70eaf5bf4c50e171d107223e3baf)", revisar se tipos os arquivos com o tipo de página "locker" foram removidos e substituidos por "type", entre outras coisas, não modifiacr os arquivos que já existem no projeto, apernas a nova inserção de novos!

2022-04-07 23:15 UTC, danielmbrasil commented
@AlexandroLuis favor requisitar alterações e não simplesmente fechar o PR. Quando as alterações forem atendidas você volta e revisa. Eu ainda estou fazendo a minha parte da revisão.

2022-04-07 23:42 UTC, AlexandroLuis commented
Seria bom um pull request com apenas novas inclusões, sem alterações e remoções dos arquivos que foram mandados, pois ali está sendo mandado um arquivo e já sendo removido na msm PL

2022-04-07 23:45 UTC, AlexandroLuis commented
Como por exemplo a seguir,
![cvbcvb](https://user-images.githubusercontent.com/52381045/162336861-09c24653-96f1-4e68-8c48-b112c45531f8.png)
Onde foi criado o arquivo, deletado e criado denovo. O ideal seria apenas o arquivo final, sem as alterações.

2022-04-08 14:04 UTC, danielmbrasil requested changes

2022-04-08 14:04 UTC, danielmbrasil commented on posts/gincana.md
> +A Gincana de Programação é uma atividade lúdica, que envolve resolução de problemas e programação de computadores. Destinada a alunos que sabem programar, é prova é constituída por problemas de vário
Corrigir a parte que diz "é prova é" para "a prova é".

2022-04-08 14:04 UTC, danielmbrasil commented on posts/treinamento.md
> +O objetivo dos conteudos abaixo é possibilitar que os interessados em aprender programacao, seguindo o modelo da programacao competitiva, possam iniciar essa jornada.
corrigir "programacao" para "programação". Está escrito duas vezes errado.

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/classe_problemas.md
> +**Estruturas e Bibliotecas** São problemas que fazem utilização de estruturas bem definidas na literatura (p.e. Lista, Pilha, Fila, Árvore, Mapas, etc) e que podem ser facilmente encontradas em livro
Corrigir "internet" para "Internet".

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/erros_comuns.md
> +É muito comum se frustrar com os erros do seu código, e isso não some com o tempo, porem, quando mais se pratica mais fácil fica de se identificar e corrigir esses erros de formas muito mais fáceis e
Corrigir "porem" para "porém". Corrigir "quando mais se pratica" para "quanto mais se pratica"

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/formato_problemas.md
> +Esse mesmo formato é adotado em outras competições, tal como a Maratona de Programação da SBC, que segue os moldes da ICPC - ACM. Há vários sistemas de treinamento online que também seguem esse padrã
Corrigir "Uri" para "Beecrowd".

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +title: Sistemas automaticos
Corrigir "automaticos" para "automáticos"

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +button: Sistemas automaticos
Corrigir "automaticos" para "automáticos"

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +A URI Online Judge é um projeto desenvolvido pelo departamento de ciência da computação da universidade URI. Esse portal apresenta um repositório com diversos problemas com diversos níveis de dificul
Informar que URI Online Judge é agora conhecido como Beecrowd.

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +### 1 - Numero
Corrigir de "numero" para "número"

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +Esse numero é o numero referente ao problema, é ele quem identifica qual é o problema na hora de enviar a resolução para avaliação. Você também consegue acessar a pagina referente ao problema com ess
Corrigir "numero" para "número", "pagina" para "página"

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +Ao realizar a correção do seu código, o próprio sistema irá inserir os dados e analisar os resultados obtidos. Por mais que seu código responda corretamente, os problemas tem um "tempo limite" de exe
Corrigir "então se seu código" para "então, se seu código". Corrigir "Porem esse não é" para "Porém, esse não é".

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +Nesse campo você deve selecionar em qual linguagem você escreveu o código que irá enviar para analise.
Corrigir "analise" para "análise".

2022-04-08 14:04 UTC, danielmbrasil commented on programacao_competitiva/sistema_automaticos.md
> +Aqui você deve colar o código que escreveu para resolver o problema, incluindo as bibliotecas utilizadas. Não é recomendado escrever o código diretamente nessa área pois você pode perde-lo. Recomenda
Corrigir "perde-lo" para "perdê-lo".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/comparar_arquivos.md
> +A ferramenta diff provavelmente já estará na sua distribuição linux assim que você instalar o sistema operacional. Mas o colordiff geralmente não é distribuído junto. Você pode instalar o pacote pelo
Corrigir "linux" para "Linux".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/entrada_saida.md
> +title: Entrada e saida
Corrigir "saida" para "saída".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/entrada_saida.md
> +button: Entrada e saida
Corrigir "saida" para "saída".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/entrada_saida.md
> +Para praticar, resolva os seguintes problemas na plataforma Uri:
Trocar "Uri" por "Beecrowd".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_repeticao.md
> +title: Estrutura de repeticao
Corrigir "repeticao" para "repetição".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_repeticao.md
> +button: Estrutura de repeticao
Corrigir "repeticao" para "repetição".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_repeticao.md
> +<p>As estruturas de repetição também são conhecidas como laços (loops) e são utilizados para executar, repetidamente, uma instrução ou bloco de instrução enquanto determinada condição estiver sendo s
Padronizar para md o que for possível. Quase todo esse arquivo está em HTML.

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_repeticao.md
> +<h3><span class="mw-headline" id="Exemplo">Exemplo</span></h3>
Apesar que esse link ainda redireciona ao beecrowd, recomendo mudá-lo porque não se sabe até quando eles manterão esse redirecionamento.

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_repeticao.md
> +<h3><span class="mw-headline" id="Problemas">Problemas</span></h3>
Mudar todos os links desta seção.

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_selecao.md
> +title: Estrutura de selecao
Corrigir "selecao" para "seleção".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_selecao.md
> +button: Estrutura de selecao
Corrigir "selecao" para "seleção".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/estruturas_selecao.md
> +# Estrutura de seleção
Padronizar esse documento para md, revisar os links a conteúdos externos.

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/operadores_logicos.md
> +button: Operadores logicos
Corrigir "logicos" para "lógicos".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/operadores_logicos.md
> +title: Operadores
Acredito que o título deveria ser "Operadores Lógicos".

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/operadores_logicos.md
> +<p>As estruturas de programação, como a  estrutura de seleção e a  estrutura de repetição</a> podem mudar o comportamento de um código. Dependendo de como o código está montado essas estruturas permi
Padronizar esse documento para md.

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/redirecionamento_entrada.md
> +![image](https://user-images.githubusercontent.com/65428645/160487260-68b3e0f2-51b2-4c49-8196-37f7ea031cda.png)
Essa URL ainda existe? Colocar essa (e demais imagens) nos assets. Nunca se sabe quando esses links externos deixarão de funcionar.

2022-04-08 14:04 UTC, danielmbrasil commented on treinamento/vetores.md
> +---
Padronizar este documento para md e verificar a disponibilidade e corretude dos links externos.

2022-04-09 00:54 UTC, danielmbrasil approved these changes

2022-04-09 00:58 UTC, merged